version: "2.7"

services:
  db:
    image: postgres:14-alpine
    env_file: .env
    container_name: db
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: on-failure
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"

  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    container_name: api
    restart: on-failure
    depends_on:
      - db
    command: ["yarn", "start"]
    entrypoint: ["./entrypoint.sh"]
    ports:
      - "5000:5000"


volumes:
  pgdata:
