#!/usr/bin/env bash
. "$(dirname -- "$0")/_/husky.sh"

set -o errexit

readonly APPNAME="incident-reporter"

# echo building....
# yarn build
# echo building completed

# echo deleting dist folder
# rm -rf dist
# echo deleting done
